
### GET all without limits or pagnation
GET http://localhost:8080/all

### GET all with limit and pagnation
GET http://localhost:8080/all/25/1

### GET by name
GET http://localhost:8080/name/luffy

### GET by id
GET http://localhost:8080/id/1

### GET by set
GET http://localhost:8080/set/champ

### GET by color
GET http://localhost:8080/color/red